name: Asset size

on: [pull_request]

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: mydea/simple-asset-size-reporter
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: '["dist/*.js"]'
          with-same: "false"
          build-assets: "npm run install-build"
